### ISSUE TITLE
test2 com resultados diferindo

### ISSUE THREAD

**Issue by raphaelsaavedra** [OptimizationPUCRio/MIPTests.jl#13]
O test2 está da seguinte forma:

`@test getobjectivevalue(m) == 9.340000000000002`
`@test getvalue(x) == [3.75, 2.5]`
`@test getvalue(u) == 1`

Meu solver está retornando:
>m.objVal
9.34

>m.colVal
Float64[3]
3.7500000000000004
2.50
1.00

Se alguém puder verificar o porquê dessa divergência eu agradeço

**Comment by raphaelsaavedra** [comment]
@andrewrosemberg

**Comment by joaquimg** [comment]
Usa o approx igual nos outros testes!

**Comment by joaquimg** [comment]
O erro é puramente numérico. Basta usar o `≈` em vez do `==`

**Comment by raphaelsaavedra** [comment]
Andrew corrigiu, vou fechar aqui.
